name: 'Close stale issues'
on:
  schedule:
    - cron: '00 14 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-pr-stale: -1
          days-before-issue-stale: 1
          days-before-pr-close: -1
          days-before-issue-close: 1
          stale-issue-message: 'This issue is stale because it has been open for 1 days with no activity.'
          close-issue-message: 'This issue is closed because it has been open for 1 days with stale.'
          stale-issue-label: 'stale'
          only-issue-labels: duplicate,invalid,wontfix
